In [1]:
#No_1
import numpy as np
x=np.array([[4,89,3],[5,56,+2]])
print("x:\n{}".format(x))

x:
[[ 4 89  3]
 [ 5 56  2]]


In [3]:
#No_2
from scipy import sparse
import numpy as np
eye=np.eye(4)
print("x:\n{}".format(eye))

x:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
#No_3
import pandas as pd
data={'product name':["pen","chalk","duster","marker"],
      'availability':["No","No","Yes","No"],
      'product no':[178,341,8,88]
    }
datap=pd.DataFrame(data)
display(datap)

product name availability  product no
0          pen           No         178
1        chalk           No         341
2       duster          Yes           8
3       marker           No          88

In [12]:
#No_4
import pandas as pd
data={'product name':["pen","chalk","duster","marker"],
      'availability':["No","No","Yes","No"],
      'product_no':[178,341,8,88]
    }
datap=pd.DataFrame(data)
test = datap[(datap['product_no'] >100)]
display(test)

product name availability  product_no
0          pen           No         178
1        chalk           No         341